title: Zahra Khanalizadeh
logo: assets/images/Zahra portrait Nov 2025 sqr.JPG
description: Welcome to my personal website!

theme: jekyll-theme-minimal

baseurl: "" 
url: "https://zahrakhanalizade.github.io/"
